name: Optimize, Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v2

      - name: Run optimization and audit
        shell: pwsh
        run: |
          pwsh -NoProfile -ExecutionPolicy Bypass -File ./site/optimize-and-build.ps1 -Root "$GITHUB_WORKSPACE/site" -BaseUrl "https://yourdomain.example" -FailOnError

      - name: Commit and push changes (if any)
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Auto: site audit fixes and build" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/dist
