name: Optimize, Build and Deploy to GitHub Pages (deprecated)

on:
  # Manual trigger only; superseded by deploy-pages.yml using official Pages actions
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      # pwsh is available by default on ubuntu-latest runners; no setup step needed

      - name: Run optimization and audit
        shell: pwsh
        run: |
          ./optimize-and-build.ps1 -Root "$env:GITHUB_WORKSPACE" -BaseUrl "https://www.448Plumbing.com" -FailOnError

      - name: Upload audit and SEO reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: site-reports
          path: |
            site-audit-report.json
            seo-report.json

      - name: Commit and push changes (if any)
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Auto: site audit fixes and build" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.448Plumbing.com
